### ISSUE TITLE
bug: opened window width is not app actual width

### ISSUE THREAD

**Issue by linonetwo** [catdad/puptron#5]
This is using puptron:

<img width="1214" alt="Screen Shot 2021-04-18 at 18 16 56" src="https://user-images.githubusercontent.com/3746270/115142063-43414900-a072-11eb-8fae-f85b8b098415.png">

This is directly open the app:

<img width="1211" alt="Screen Shot 2021-04-18 at 18 17 30" src="https://user-images.githubusercontent.com/3746270/115142080-57854600-a072-11eb-8bb4-a8a7f5c192a9.png">

```ts
import path from 'path';
import { launch } from 'puptron';

const projectRoot = path.join(__dirname, '..', '..');
const packageName = process.env.npm_package_name ?? 'TiddlyGit';
async function start(): Promise<void> {
  // path: path.join(
  //   projectRoot,
  //   // The path to the binary depends on your platform and architecture
  //   `out/${packageName}-darwin-x64/${packageName}.app/Contents/MacOS/${packageName}`,
  // ),
  const chromeDriverArgs = ['--disable-extensions'];
  const args = [path.join(projectRoot, '.webpack', 'main', 'index.js')];
  const env = {
    NODE_ENV: 'test',
  };
  const stdio = ['inherit', 'inherit', 'inherit', 'ipc'];
  const app = await launch(args, {
    cwd: projectRoot,
    env,
  });
}
start();

```

PS. how to use chromeDriverArgs like spectron?

**Comment by catdad** [comment]
This issue is technically how `puppeteer` is meant to work, but it is in fact pretty weird. It is fixed in 0.0.7.
